
-- Create a table for pending builder tasks
create table pending_builder_tasks (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  area text,
  is_urgent boolean default false,
  comments text,
  user_id uuid references auth.users not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Set up Row Level Security (RLS)
alter table pending_builder_tasks enable row level security;

-- Policy: Users can view their own tasks
create policy "Users can view their own pending tasks"
  on pending_builder_tasks for select
  using (auth.uid() = user_id);

-- Policy: Users can insert their own tasks
create policy "Users can insert their own pending tasks"
  on pending_builder_tasks for insert
  with check (auth.uid() = user_id);

-- Policy: Users can update their own tasks
create policy "Users can update their own pending tasks"
  on pending_builder_tasks for update
  using (auth.uid() = user_id);

-- Policy: Users can delete their own tasks
create policy "Users can delete their own pending tasks"
  on pending_builder_tasks for delete
  using (auth.uid() = user_id);
