
-- Create a table for emergency contacts
create table if not exists emergency_contacts (
  id bigint generated by default as identity primary key,
  electrician text,
  plumber text,
  security text,
  project_manager text,
  association_contact text,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_by uuid references auth.users
);

-- RLS
alter table emergency_contacts enable row level security;

-- Drop existing policies to ensure clean state if re-running
drop policy if exists "Anyone can view emergency contacts" on emergency_contacts;
drop policy if exists "Authenticated users can insert emergency contacts" on emergency_contacts;
drop policy if exists "Authenticated users can update emergency contacts" on emergency_contacts;
drop policy if exists "Admins can insert emergency contacts" on emergency_contacts;
drop policy if exists "Admins can update emergency contacts" on emergency_contacts;


-- Allow everyone to view
create policy "Anyone can view emergency contacts"
  on emergency_contacts for select
  using (true);

-- Allow ONLY admins to insert/update
-- Assuming 'role' is stored in user_metadata

create policy "Admins can insert emergency contacts"
  on emergency_contacts for insert
  with check (
    auth.role() = 'authenticated' and
    (auth.jwt() -> 'user_metadata' ->> 'role') = 'admin'
  );

create policy "Admins can update emergency contacts"
  on emergency_contacts for update
  using (
    auth.role() = 'authenticated' and
    (auth.jwt() -> 'user_metadata' ->> 'role') = 'admin'
  );
