
-- Create a table for wishlist items
create table wishlist_items (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  area text,
  is_urgent boolean default false,
  comments text,
  user_id uuid references auth.users not null,
  created_by uuid references auth.users, -- Track who created
  last_edited_by uuid references auth.users, -- Track who last edited
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Add tracking columns to pending_builder_tasks if not exists (migrating existing table)
alter table pending_builder_tasks 
add column if not exists created_by uuid references auth.users,
add column if not exists last_edited_by uuid references auth.users;

-- Set up Row Level Security (RLS) for wishlist
alter table wishlist_items enable row level security;

-- Policy: Users can view their own wishlist items (and maybe others in future, but stick to own for now as per pattern)
-- Wait, if it's a shared wishlist for the apartment, maybe everyone should see it? 
-- The prompt implies "capture user who added or edited" which suggests a shared list or audit trail.
-- For now, I'll stick to the "personal" or "household" scope implemented in pending-builder, which was enforcing owner access.
-- However, "capture user who added" implies multiple people might be adding to a shared list. 
-- Changing RLS to allow all authenticated users to view/edit for a "Community" app feel, or sticking to private?
-- "Residents to have user roles... residents and admin". 
-- Let's make it so residents can see all items, but tracking is important.

-- RLS for Wishlist (Allow all authenticated users to read/create/update/delete for now, but track them)
create policy "Authenticated users can select wishlist items"
  on wishlist_items for select
  using (auth.role() = 'authenticated');

create policy "Authenticated users can insert wishlist items"
  on wishlist_items for insert
  with check (auth.role() = 'authenticated');

create policy "Authenticated users can update wishlist items"
  on wishlist_items for update
  using (auth.role() = 'authenticated');

create policy "Authenticated users can delete wishlist items"
  on wishlist_items for delete
  using (auth.role() = 'authenticated');

-- Update RLS for Pending Builder Tasks if we want to track 'created_by' in a shared context
-- For now preserving the 'personal' nature of pending_builder_tasks unless specified otherwise, 
-- BUT the request says "capture user who added", which suggests checking that column.

